/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentRegistrySol from "./AgentRegistry.sol";
export type { agentRegistrySol };
import type * as clawgerManagerSol from "./ClawgerManager.sol";
export type { clawgerManagerSol };
import type * as registryWiringHelperSol from "./RegistryWiringHelper.sol";
export type { registryWiringHelperSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { CLAWGERToken } from "./CLAWGERToken";
