/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClawgerManager,
  IClawgerManagerInterface,
} from "../../../contracts/RegistryWiringHelper.sol/IClawgerManager";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "registry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IClawgerManager__factory {
  static readonly abi = _abi;
  static createInterface(): IClawgerManagerInterface {
    return new Interface(_abi) as IClawgerManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClawgerManager {
    return new Contract(address, _abi, runner) as unknown as IClawgerManager;
  }
}
