/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AgentRegistryV3 {
  export type AgentStruct = {
    wallet: AddressLike;
    agentType: BigNumberish;
    capabilities: BytesLike[];
    minFee: BigNumberish;
    minBond: BigNumberish;
    operator: AddressLike;
    reputation: BigNumberish;
    active: boolean;
    exists: boolean;
    registeredAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type AgentStructOutput = [
    wallet: string,
    agentType: bigint,
    capabilities: string[],
    minFee: bigint,
    minBond: bigint,
    operator: string,
    reputation: bigint,
    active: boolean,
    exists: boolean,
    registeredAt: bigint,
    updatedAt: bigint
  ] & {
    wallet: string;
    agentType: bigint;
    capabilities: string[];
    minFee: bigint;
    minBond: bigint;
    operator: string;
    reputation: bigint;
    active: boolean;
    exists: boolean;
    registeredAt: bigint;
    updatedAt: bigint;
  };
}

export interface AgentRegistryV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_REPUTATION"
      | "MAX_CAPABILITIES"
      | "acceptManagerRole"
      | "deactivate"
      | "getAgent"
      | "getCapabilities"
      | "getReputation"
      | "hasCapability"
      | "isActive"
      | "manager"
      | "owner"
      | "pause"
      | "paused"
      | "pendingManager"
      | "proposeManager"
      | "reactivate"
      | "registerAgent"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "updateAgent"
      | "updateReputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentReactivated"
      | "AgentRegistered"
      | "AgentUpdated"
      | "ManagerUpdateProposed"
      | "ManagerUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CAPABILITIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptManagerRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapabilities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCapability",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BigNumberish, BytesLike[], BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [BigNumberish, BigNumberish, BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CAPABILITIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptManagerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reactivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReactivatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    agentType: BigNumberish,
    minFee: BigNumberish,
    minBond: BigNumberish,
    capabilities: BytesLike[]
  ];
  export type OutputTuple = [
    agent: string,
    agentType: bigint,
    minFee: bigint,
    minBond: bigint,
    capabilities: string[]
  ];
  export interface OutputObject {
    agent: string;
    agentType: bigint;
    minFee: bigint;
    minBond: bigint;
    capabilities: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    minFee: BigNumberish,
    minBond: BigNumberish,
    capabilities: BytesLike[],
    operator: AddressLike
  ];
  export type OutputTuple = [
    agent: string,
    minFee: bigint,
    minBond: bigint,
    capabilities: string[],
    operator: string
  ];
  export interface OutputObject {
    agent: string;
    minFee: bigint;
    minBond: bigint;
    capabilities: string[];
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerUpdateProposedEvent {
  export type InputTuple = [newManager: AddressLike];
  export type OutputTuple = [newManager: string];
  export interface OutputObject {
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    agent: string,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    agent: string;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistryV3 extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistryV3;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MAX_CAPABILITIES: TypedContractMethod<[], [bigint], "view">;

  acceptManagerRole: TypedContractMethod<[], [void], "nonpayable">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agentAddr: AddressLike],
    [AgentRegistryV3.AgentStructOutput],
    "view"
  >;

  getCapabilities: TypedContractMethod<
    [agentAddr: AddressLike],
    [string[]],
    "view"
  >;

  getReputation: TypedContractMethod<
    [agentAddr: AddressLike],
    [bigint],
    "view"
  >;

  hasCapability: TypedContractMethod<
    [agentAddr: AddressLike, capability: BytesLike],
    [boolean],
    "view"
  >;

  isActive: TypedContractMethod<[agentAddr: AddressLike], [boolean], "view">;

  manager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingManager: TypedContractMethod<[], [string], "view">;

  proposeManager: TypedContractMethod<
    [newManager: AddressLike],
    [void],
    "nonpayable"
  >;

  reactivate: TypedContractMethod<[], [void], "nonpayable">;

  registerAgent: TypedContractMethod<
    [
      agentType: BigNumberish,
      capabilities: BytesLike[],
      minFee: BigNumberish,
      minBond: BigNumberish,
      operator: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAgent: TypedContractMethod<
    [
      newMinFee: BigNumberish,
      newMinBond: BigNumberish,
      newCapabilities: BytesLike[],
      newOperator: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agentAddr: AddressLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CAPABILITIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptManagerRole"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentAddr: AddressLike],
    [AgentRegistryV3.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCapabilities"
  ): TypedContractMethod<[agentAddr: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[agentAddr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCapability"
  ): TypedContractMethod<
    [agentAddr: AddressLike, capability: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[agentAddr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeManager"
  ): TypedContractMethod<[newManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      agentType: BigNumberish,
      capabilities: BytesLike[],
      minFee: BigNumberish,
      minBond: BigNumberish,
      operator: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      newMinFee: BigNumberish,
      newMinBond: BigNumberish,
      newCapabilities: BytesLike[],
      newOperator: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentAddr: AddressLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentReactivated"
  ): TypedContractEvent<
    AgentReactivatedEvent.InputTuple,
    AgentReactivatedEvent.OutputTuple,
    AgentReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerUpdateProposed"
  ): TypedContractEvent<
    ManagerUpdateProposedEvent.InputTuple,
    ManagerUpdateProposedEvent.OutputTuple,
    ManagerUpdateProposedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerUpdated"
  ): TypedContractEvent<
    ManagerUpdatedEvent.InputTuple,
    ManagerUpdatedEvent.OutputTuple,
    ManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentReactivated(address)": TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;
    AgentReactivated: TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,uint8,uint256,uint256,bytes32[])": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,uint256,uint256,bytes32[],address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "ManagerUpdateProposed(address)": TypedContractEvent<
      ManagerUpdateProposedEvent.InputTuple,
      ManagerUpdateProposedEvent.OutputTuple,
      ManagerUpdateProposedEvent.OutputObject
    >;
    ManagerUpdateProposed: TypedContractEvent<
      ManagerUpdateProposedEvent.InputTuple,
      ManagerUpdateProposedEvent.OutputTuple,
      ManagerUpdateProposedEvent.OutputObject
    >;

    "ManagerUpdated(address,address)": TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;
    ManagerUpdated: TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256,string)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
