/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as agentRegistrySol from "./AgentRegistry.sol";
export * as clawgerManagerSol from "./ClawgerManager.sol";
export * as registryWiringHelperSol from "./RegistryWiringHelper.sol";
export * as mocks from "./mocks";
export { CLAWGERToken__factory } from "./CLAWGERToken__factory";
