/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ClawgerManagerV4Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCEPT_PROPOSAL_TYPEHASH"
      | "BOND_BURN_PERCENT"
      | "BURN_ADDRESS"
      | "CLGR"
      | "MAX_ESCROW"
      | "MAX_OBJECTIVE_LENGTH"
      | "MIN_WORKER_BOND"
      | "PROPOSAL_BOND"
      | "REJECT_PROPOSAL_TYPEHASH"
      | "TASK_EXPIRY_DURATION"
      | "acceptProposalWithSignature"
      | "acceptRegistryManagerRole"
      | "clawger"
      | "eip712Domain"
      | "expireTask"
      | "getAcceptProposalHash"
      | "getDomainSeparator"
      | "getRejectProposalHash"
      | "lockedWorkerBond"
      | "owner"
      | "pause"
      | "paused"
      | "postWorkerBond"
      | "proposalCounter"
      | "proposalProcessed"
      | "proposals"
      | "registry"
      | "rejectProposalWithSignature"
      | "startTask"
      | "submitProposal"
      | "submitWork"
      | "taskCounter"
      | "tasks"
      | "unpause"
      | "verifyTask"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "Paused"
      | "ProposalAccepted"
      | "ProposalRejected"
      | "ProposalSubmitted"
      | "TaskCompleted"
      | "TaskExpired"
      | "TaskSettled"
      | "TaskStarted"
      | "Unpaused"
      | "WorkerBondPosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCEPT_PROPOSAL_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BOND_BURN_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BURN_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CLGR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_ESCROW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_OBJECTIVE_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WORKER_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REJECT_PROPOSAL_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TASK_EXPIRY_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptProposalWithSignature",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptRegistryManagerRole",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "clawger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expireTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAcceptProposalHash",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRejectProposalHash",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedWorkerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postWorkerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalProcessed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectProposalWithSignature",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyTask",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCEPT_PROPOSAL_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BOND_BURN_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BURN_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CLGR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_ESCROW", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_OBJECTIVE_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WORKER_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REJECT_PROPOSAL_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TASK_EXPIRY_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptProposalWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptRegistryManagerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clawger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expireTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAcceptProposalHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRejectProposalHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedWorkerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postWorkerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectProposalWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taskCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyTask", data: BytesLike): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalAcceptedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    taskId: BigNumberish,
    worker: AddressLike,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    taskId: bigint,
    worker: string,
    verifier: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    taskId: bigint;
    worker: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRejectedEvent {
  export type InputTuple = [proposalId: BigNumberish, reason: string];
  export type OutputTuple = [proposalId: bigint, reason: string];
  export interface OutputObject {
    proposalId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSubmittedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    escrow: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    escrow: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    escrow: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExpiredEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSettledEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    success: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, success: boolean, payout: bigint];
  export interface OutputObject {
    taskId: bigint;
    success: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskStartedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerBondPostedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClawgerManagerV4 extends BaseContract {
  connect(runner?: ContractRunner | null): ClawgerManagerV4;
  waitForDeployment(): Promise<this>;

  interface: ClawgerManagerV4Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCEPT_PROPOSAL_TYPEHASH: TypedContractMethod<[], [string], "view">;

  BOND_BURN_PERCENT: TypedContractMethod<[], [bigint], "view">;

  BURN_ADDRESS: TypedContractMethod<[], [string], "view">;

  CLGR: TypedContractMethod<[], [string], "view">;

  MAX_ESCROW: TypedContractMethod<[], [bigint], "view">;

  MAX_OBJECTIVE_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MIN_WORKER_BOND: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_BOND: TypedContractMethod<[], [bigint], "view">;

  REJECT_PROPOSAL_TYPEHASH: TypedContractMethod<[], [string], "view">;

  TASK_EXPIRY_DURATION: TypedContractMethod<[], [bigint], "view">;

  acceptProposalWithSignature: TypedContractMethod<
    [
      proposalId: BigNumberish,
      worker: AddressLike,
      verifier: AddressLike,
      workerBond: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  acceptRegistryManagerRole: TypedContractMethod<[], [void], "nonpayable">;

  clawger: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  expireTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  getAcceptProposalHash: TypedContractMethod<
    [
      proposalId: BigNumberish,
      worker: AddressLike,
      verifier: AddressLike,
      workerBond: BigNumberish,
      deadline: BigNumberish
    ],
    [string],
    "view"
  >;

  getDomainSeparator: TypedContractMethod<[], [string], "view">;

  getRejectProposalHash: TypedContractMethod<
    [proposalId: BigNumberish, reason: string, deadline: BigNumberish],
    [string],
    "view"
  >;

  lockedWorkerBond: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  postWorkerBond: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposalCounter: TypedContractMethod<[], [bigint], "view">;

  proposalProcessed: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        proposer: string;
        objective: string;
        escrow: bigint;
        deadline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  rejectProposalWithSignature: TypedContractMethod<
    [
      proposalId: BigNumberish,
      reason: string,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  startTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  submitProposal: TypedContractMethod<
    [objective: string, escrowAmount: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  taskCounter: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        worker: string;
        verifier: string;
        escrow: bigint;
        workerBond: bigint;
        status: bigint;
        settled: boolean;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyTask: TypedContractMethod<
    [taskId: BigNumberish, success: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCEPT_PROPOSAL_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BOND_BURN_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BURN_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CLGR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_ESCROW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_OBJECTIVE_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WORKER_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REJECT_PROPOSAL_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TASK_EXPIRY_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptProposalWithSignature"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      worker: AddressLike,
      verifier: AddressLike,
      workerBond: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "acceptRegistryManagerRole"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clawger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "expireTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAcceptProposalHash"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      worker: AddressLike,
      verifier: AddressLike,
      workerBond: BigNumberish,
      deadline: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDomainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRejectProposalHash"
  ): TypedContractMethod<
    [proposalId: BigNumberish, reason: string, deadline: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockedWorkerBond"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "postWorkerBond"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalProcessed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        proposer: string;
        objective: string;
        escrow: bigint;
        deadline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectProposalWithSignature"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      reason: string,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [objective: string, escrowAmount: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        worker: string;
        verifier: string;
        escrow: bigint;
        workerBond: bigint;
        status: bigint;
        settled: boolean;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, success: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalAccepted"
  ): TypedContractEvent<
    ProposalAcceptedEvent.InputTuple,
    ProposalAcceptedEvent.OutputTuple,
    ProposalAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRejected"
  ): TypedContractEvent<
    ProposalRejectedEvent.InputTuple,
    ProposalRejectedEvent.OutputTuple,
    ProposalRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSubmitted"
  ): TypedContractEvent<
    ProposalSubmittedEvent.InputTuple,
    ProposalSubmittedEvent.OutputTuple,
    ProposalSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskExpired"
  ): TypedContractEvent<
    TaskExpiredEvent.InputTuple,
    TaskExpiredEvent.OutputTuple,
    TaskExpiredEvent.OutputObject
  >;
  getEvent(
    key: "TaskSettled"
  ): TypedContractEvent<
    TaskSettledEvent.InputTuple,
    TaskSettledEvent.OutputTuple,
    TaskSettledEvent.OutputObject
  >;
  getEvent(
    key: "TaskStarted"
  ): TypedContractEvent<
    TaskStartedEvent.InputTuple,
    TaskStartedEvent.OutputTuple,
    TaskStartedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerBondPosted"
  ): TypedContractEvent<
    WorkerBondPostedEvent.InputTuple,
    WorkerBondPostedEvent.OutputTuple,
    WorkerBondPostedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProposalAccepted(uint256,uint256,address,address)": TypedContractEvent<
      ProposalAcceptedEvent.InputTuple,
      ProposalAcceptedEvent.OutputTuple,
      ProposalAcceptedEvent.OutputObject
    >;
    ProposalAccepted: TypedContractEvent<
      ProposalAcceptedEvent.InputTuple,
      ProposalAcceptedEvent.OutputTuple,
      ProposalAcceptedEvent.OutputObject
    >;

    "ProposalRejected(uint256,string)": TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;
    ProposalRejected: TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;

    "ProposalSubmitted(uint256,address,uint256,uint256)": TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;
    ProposalSubmitted: TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;

    "TaskCompleted(uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskExpired(uint256)": TypedContractEvent<
      TaskExpiredEvent.InputTuple,
      TaskExpiredEvent.OutputTuple,
      TaskExpiredEvent.OutputObject
    >;
    TaskExpired: TypedContractEvent<
      TaskExpiredEvent.InputTuple,
      TaskExpiredEvent.OutputTuple,
      TaskExpiredEvent.OutputObject
    >;

    "TaskSettled(uint256,bool,uint256)": TypedContractEvent<
      TaskSettledEvent.InputTuple,
      TaskSettledEvent.OutputTuple,
      TaskSettledEvent.OutputObject
    >;
    TaskSettled: TypedContractEvent<
      TaskSettledEvent.InputTuple,
      TaskSettledEvent.OutputTuple,
      TaskSettledEvent.OutputObject
    >;

    "TaskStarted(uint256)": TypedContractEvent<
      TaskStartedEvent.InputTuple,
      TaskStartedEvent.OutputTuple,
      TaskStartedEvent.OutputObject
    >;
    TaskStarted: TypedContractEvent<
      TaskStartedEvent.InputTuple,
      TaskStartedEvent.OutputTuple,
      TaskStartedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WorkerBondPosted(uint256,address,uint256)": TypedContractEvent<
      WorkerBondPostedEvent.InputTuple,
      WorkerBondPostedEvent.OutputTuple,
      WorkerBondPostedEvent.OutputObject
    >;
    WorkerBondPosted: TypedContractEvent<
      WorkerBondPostedEvent.InputTuple,
      WorkerBondPostedEvent.OutputTuple,
      WorkerBondPostedEvent.OutputObject
    >;
  };
}
