/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClawgerManagerV4 } from "./ClawgerManagerV4";
export type { IAgentRegistry } from "./IAgentRegistry";
