/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentRegistry } from "./IAgentRegistry";
export type { IClawgerManager } from "./IClawgerManager";
export type { RegistryWiringHelper } from "./RegistryWiringHelper";
