/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RegistryWiringHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRegistryAddress"
      | "isManagerOwner"
      | "wireRegistryManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "WiringCompleted" | "WiringFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getRegistryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManagerOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wireRegistryManager",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManagerOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wireRegistryManager",
    data: BytesLike
  ): Result;
}

export namespace WiringCompletedEvent {
  export type InputTuple = [registry: AddressLike, manager: AddressLike];
  export type OutputTuple = [registry: string, manager: string];
  export interface OutputObject {
    registry: string;
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WiringFailedEvent {
  export type InputTuple = [
    registry: AddressLike,
    manager: AddressLike,
    reason: string
  ];
  export type OutputTuple = [registry: string, manager: string, reason: string];
  export interface OutputObject {
    registry: string;
    manager: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RegistryWiringHelper extends BaseContract {
  connect(runner?: ContractRunner | null): RegistryWiringHelper;
  waitForDeployment(): Promise<this>;

  interface: RegistryWiringHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRegistryAddress: TypedContractMethod<
    [managerAddress: AddressLike],
    [string],
    "view"
  >;

  isManagerOwner: TypedContractMethod<
    [managerAddress: AddressLike],
    [boolean],
    "view"
  >;

  wireRegistryManager: TypedContractMethod<
    [managerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRegistryAddress"
  ): TypedContractMethod<[managerAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isManagerOwner"
  ): TypedContractMethod<[managerAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "wireRegistryManager"
  ): TypedContractMethod<[managerAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "WiringCompleted"
  ): TypedContractEvent<
    WiringCompletedEvent.InputTuple,
    WiringCompletedEvent.OutputTuple,
    WiringCompletedEvent.OutputObject
  >;
  getEvent(
    key: "WiringFailed"
  ): TypedContractEvent<
    WiringFailedEvent.InputTuple,
    WiringFailedEvent.OutputTuple,
    WiringFailedEvent.OutputObject
  >;

  filters: {
    "WiringCompleted(address,address)": TypedContractEvent<
      WiringCompletedEvent.InputTuple,
      WiringCompletedEvent.OutputTuple,
      WiringCompletedEvent.OutputObject
    >;
    WiringCompleted: TypedContractEvent<
      WiringCompletedEvent.InputTuple,
      WiringCompletedEvent.OutputTuple,
      WiringCompletedEvent.OutputObject
    >;

    "WiringFailed(address,address,string)": TypedContractEvent<
      WiringFailedEvent.InputTuple,
      WiringFailedEvent.OutputTuple,
      WiringFailedEvent.OutputObject
    >;
    WiringFailed: TypedContractEvent<
      WiringFailedEvent.InputTuple,
      WiringFailedEvent.OutputTuple,
      WiringFailedEvent.OutputObject
    >;
  };
}
